export const SIMULATION_VERSION = "1" as const;

export * from "./day/day-context";
export * from "./day/simulate-day";
export * from "./day/world-invariants";
export * from "./deck-evolution/adoption";
export * from "./deck-evolution/deck-builder";
export * from "./deck-evolution/deck-genome";
export { appendCashEntry } from "./economy/cash-ledger";
export * from "./history/daily-report";
export * from "./market/call-auction";
export * from "./market/deck-cost";
export * from "./market/market-intents";
export * from "./meta/meta-aggregation";
export * from "./meta/sample-matches";
export * from "./metrics/accessibility";
export * from "./metrics/ecosystem-risk";
export * from "./metrics/satisfaction";
export * from "./metrics/world-metrics";
export * from "./operations/scheduler";
export * from "./operations/expansion-pipeline";
export * from "./operations/playtest";
export * from "./population/create-population";
export * from "./population/lifecycle";
export * from "./products/open-product";
export * from "./products/primary-market";
export * from "./products/product-lifecycle";
export * from "./products/product-value";
export * from "./products/production";
export * from "./products/releases";
export * from "./products/reprints";
export * from "./society/knowledge";
