export type Brand<T, B extends string> = T & { readonly __brand: B };

export type CardId = Brand<string, "CardId">;
export type DeckId = Brand<string, "DeckId">;
export type FactionId = Brand<string, "FactionId">;
export type PlayerId = Brand<string, "PlayerId">;
export type MatchId = Brand<string, "MatchId">;
export type PrintingId = Brand<string, "PrintingId">;
export type ExpansionId = Brand<string, "ExpansionId">;
export type ProductId = Brand<string, "ProductId">;
export type PrintRunId = Brand<string, "PrintRunId">;
export type TransactionId = Brand<string, "TransactionId">;
export type TournamentId = Brand<string, "TournamentId">;
export type OperationId = Brand<string, "OperationId">;
export type AgentId = Brand<string, "AgentId">;
export type SaveId = Brand<string, "SaveId">;

export const cardId = (value: string) => value as CardId;
export const deckId = (value: string) => value as DeckId;
export const factionId = (value: string) => value as FactionId;
export const playerId = (value: string) => value as PlayerId;
export const matchId = (value: string) => value as MatchId;
export const printingId = (value: string) => value as PrintingId;
export const expansionId = (value: string) => value as ExpansionId;
export const productId = (value: string) => value as ProductId;
export const printRunId = (value: string) => value as PrintRunId;
export const transactionId = (value: string) => value as TransactionId;
export const tournamentId = (value: string) => value as TournamentId;
export const operationId = (value: string) => value as OperationId;
export const agentId = (value: string) => value as AgentId;
export const saveId = (value: string) => value as SaveId;
