export const METRICS_CONFIG = {
  accessibility: {
    weights: {
      starterAvailability: 0.2,
      starterAffordability: 0.15,
      cheapestCompetitiveDeck: 0.2,
      medianMetaDeck: 0.2,
      coreCardAvailability: 0.15,
      budgetDeckViability: 0.1,
    },
    comfortableStarterPrice: 20,
    comfortableCompetitiveDeckCost: 100,
    comfortableMedianMetaDeckCost: 150,
  },
  metaHealth: {
    weights: {
      diversity: 0.25,
      dominance: 0.25,
      winRate: 0.2,
      matchup: 0.15,
      accessibility: 0.15,
    },
    minimumReliableSamples: 10,
    winRateOutlierDistance: 0.25,
    insufficientSampleNeutralScore: 0.5,
    stalenessPenaltyPerDay: 0.5,
    maximumStalenessPenalty: 30,
  },
  responseSpeed: {
    hype: 0.35,
    collectorHeat: 0.2,
    metaHealth: 0.15,
    sentiment: 0.2,
    brandTrust: 0.05,
    satisfaction: 0.15,
  },
  satisfaction: {
    weights: {
      gameplayQuality: 0.25,
      affordability: 0.2,
      novelty: 0.15,
      trust: 0.15,
      socialActivity: 0.15,
      collectionExperience: 0.1,
    },
  },
  collectorHeat: {
    weights: {
      tradingVolume: 1 / 6,
      liquidity: 1 / 6,
      priceMomentum: 1 / 6,
      scarcityExcitement: 1 / 6,
      productFreshness: 1 / 6,
      collectorConfidence: 1 / 6,
    },
  },
  signals: {
    matchAttentionDivisor: 10,
    dissatisfactionAttentionWeight: 0.25,
    releaseNegativeAttentionPerEvent: 0.2,
    releaseTrustPenaltyPerEvent: 20,
    releaseTrustBonusPerEvent: 5,
    neutralPriceMomentum: 0.5,
    productFreshnessWithSales: 0.8,
    productFreshnessWithoutSales: 0.2,
  },
  lifecycle: {
    onboardingDays: 7,
    rates: {
      potentialToInterestedBase: 0.01,
      potentialToInterestedHypeWeight: 0.02,
      interestedToNewBase: 0.02,
      interestedToNewAccessibilityWeight: 0.08,
      newToActiveBase: 0.4,
      newToActiveSatisfactionWeight: 0.5,
      activeToAtRiskBase: 0.005,
      activeToAtRiskDissatisfactionWeight: 0.08,
      atRiskToChurnedBase: 0.02,
      atRiskToChurnedDissatisfactionWeight: 0.15,
      churnedToReturningBase: 0.002,
      churnedToReturningHypeTrustWeight: 0.02,
      returningToActiveBase: 0.4,
      returningToActiveSatisfactionWeight: 0.5,
    },
  },
  ecosystemRisk: {
    terminalActivePlayers: 100,
    terminalHype: 5,
    terminalPersistenceDays: 30,
    emergencyCreditLimit: -10_000,
    deathSpiralMinimumSignals: 5,
    decliningMinimumSignals: 4,
    strainedMinimumSignals: 2,
    minimumDeclineDaysForDeathSpiral: 14,
    weakAcquisitionToChurnRatio: 0.8,
    weakRetentionRate: 0.55,
    lowHype: 25,
    lowBrandTrust: 40,
    decliningActivePlayerTrend: -0.02,
  },
} as const;
